name: Question
description: Ask about something here.
labels: [question]
body:
  - type: textarea
    attributes:
      label: What is your question about the mod?
    validations:
      required: true
